# Generated by Django 5.2.5 on 2025-09-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['-month']},
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
