# Generated by Django 5.2.5 on 2025-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_remove_student_email_remove_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
